### ISSUE TITLE
🚗 [GRANTS] Hashing on merkel root property

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#101]
**Notes**
Hashing on merkel root property: change property name on the vc, redeploy to ceramic, want to switch from Merkel root, schema changes but no functional changes in the backend

**Dev notes**
- Schema changes: `root` changes to `hash` in VerifiableCredential
- Root value changes to - `hash: SHA256(IAM_PRIVATE_KEY + VERSION + TYPE + PII_FIELD(s))`
- Additional schema changes from Ceramic team:
  - Use `did:pkh:eip155:1:<eth-address>` instead of `did:ethr:<eth-address>`
  - Separate `#${record.type}` from `credentialSubject.id` and move to `credentialSubject.provider`

**Comment by shavinac** [comment]
the `credentialSubject.hash` field in a stamp VC (see example below) should be populated. 

previously there was a `credentialSubject.root` that held a merkle tree root holding the account information/PII of the stamp verification. we decided to move away from the merkle tree because it would be possible to associate account info (e.g. email, twitter handle, etc) <-> stamp/passport holder by attempting to reconstruct the merkle tree and checking the computed root value. for example, someone could brute-force the email address value from the VC.
see [sybil stories notion](https://gitcoin.notion.site/gitcoin/Sybil-Stories-a2ddda2bf11c42b3b9659d294e9b1760) for more context

```
{
  "provider": "Facebook",
  "credential": {
    "type": [
      "VerifiableCredential"
    ],
    "proof": {
      "jws": "eyJhbGciOiJFZERTQSIsImNyaXQiOlsiYjY0Il0sImI2NCI6ZmFsc2V9..WWC40qMUkpifwT_IDGuwHKuxEHrJ9euyMbqsqTZWBC-4yCVeG8Yhm6_ck5gCaLAH-KduOruSKDrvx3wJiIasBQ",
      "type": "Ed25519Signature2018",
      "created": "2022-06-10T21:35:34.085Z",
      "proofPurpose": "assertionMethod",
      "verificationMethod": "did:key:z6MkghvGHLobLEdj1bgRLhS4LPGJAvbMA1tn2zcRyqmYU5LC#z6MkghvGHLobLEdj1bgRLhS4LPGJAvbMA1tn2zcRyqmYU5LC"
    },
    "issuer": "did:key:z6MkghvGHLobLEdj1bgRLhS4LPGJAvbMA1tn2zcRyqmYU5LC",
    "@context": [
      "https://www.w3.org/2018/credentials/v1"
    ],
    "issuanceDate": "2022-06-10T21:35:34.085Z",
    "expirationDate": "2022-09-08T21:35:34.085Z",
    "credentialSubject": {
      "id": "did:pkh:eip155:1:0x5bd8C4Ec48cf3EFDD791B5BAb2d4869342605F98",
      "hash": "v0.0.0:gDIVp15Hdr/K1FkFKO8fs3Pc/w+ObfBm6iV5i5cqCP8=",
      "@context": [
        {
          "hash": "https://schema.org/Text",
          "provider": "https://schema.org/Text"
        }
      ],
      "provider": "Facebook"
    }
  }
}
```
