### ISSUE TITLE
[UI] in the passport app, when a passport cannot be found present an option to keep retrying the network

### ISSUE THREAD

**Issue by kevinrolsen** [gitcoinco/dPopp#196]
As a user on the Gitcoin Passport
When my passport cannot be found (timeout, error, ~~or no passport yet created~~)
I want to be presented with a modal asking "Passport not found, do you want to try fetching your passport again, ~~or create. anew one~~: 'Keep trying' ~~or 'Create new'~~

Notes:
- If Ceramic is down, should we ask people to create a Passport "with" Ceramic? Perhaps we should do [#195](https://github.com/gitcoinco/dPopp/issues/195)
- There is a difference in Ceramic in returning errors versus returning no passport

Updates re: discussion with Brent, Graham, and Shavina: 

* if Ceramic connection times out or errors, we should implement a modal with a "Keep trying" / retry option, which improves the current user experience of getting kicked back to the Passport landing page in that situation. 
* not implementing the "create new" option, since the user still wouldn't be able to actually create a new passport until Ceramic connection is good. 
* further discussion needed on "offline creating/saving" options, and outside the scope of this story.

**Comment by leoneric** [comment]
To loop in @Etovardesign

**Comment by Etovardesign** [comment]
@leoneric Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2584%3A56886

**Comment by shavinac** [comment]
discussion with Brent, Graham, and Shavina: 

* if Ceramic connection times out or errors, we should implement a modal with a "Keep trying" / retry option, which improves the current user experience of getting kicked back to the Passport landing page in that situation. 
* not implementing the "create new" option, since the user still wouldn't be able to actually create a new passport until Ceramic connection is good. further discussion needed on "offline saving" options, and outside the scope of this story.

**Comment by shavinac** [comment]
7c5390572dbc8df32b7ef4fdef570f1d6a0ae781 deployed to prod Thu, 16 Jun 2022 19:49:49 GMT
